#include <iostream>
#include <iomanip>
using namespace std;

// Function prototype
double population(double, double, double, int, int);

//ADD PROTOTYPES FOR OTHER FUNCTIONS YOU DEVELOP
//ADD PROTOTYPES FOR OTHER FUNCTIONS YOU DEVELOP
//ADD PROTOTYPES FOR OTHER FUNCTIONS YOU DEVELOP

int main()
{
	// IMPLEMENT MAIN
	// IMPLEMENT MAIN
	// IMPLEMENT MAIN
}

// IMPLEMENT THE POPULATION FUNCTION AND OTHER FUNCTIONS
// IMPLEMENT THE POPULATION FUNCTION AND OTHER FUNCTIONS
// IMPLEMENT THE POPULATION FUNCTION AND OTHER FUNCTIONS
